
package com.polarising.bootsecurity.soap.employee.example.xmlns._1564670906833;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Service", targetNamespace = "http://xmlns.example.com/1564670906833", wsdlLocation = "http://localhost:8074/bankrising/ws/employee.wsdl")
public class EmployeeService
    extends javax.xml.ws.Service
{

    private final static URL SERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICE_EXCEPTION;
    private final static QName SERVICE_QNAME = new QName("http://xmlns.example.com/1564670906833", "Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8074/bankrising/ws/employee.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICE_WSDL_LOCATION = url;
        SERVICE_EXCEPTION = e;
    }

    public EmployeeService() {
        super(__getWsdlLocation(), SERVICE_QNAME);
    }

    public EmployeeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICE_QNAME, features);
    }

    public EmployeeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE_QNAME);
    }

    public EmployeeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE_QNAME, features);
    }

    public EmployeeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeEmployee
     */
    @WebEndpoint(name = "PortType_EmployeeEndpoint1")
    public PortTypeEmployee getPortTypeEmployeeEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1564670906833", "PortType_EmployeeEndpoint1"), PortTypeEmployee.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeEmployee
     */
    @WebEndpoint(name = "PortType_EmployeeEndpoint1")
    public PortTypeEmployee getPortTypeEmployeeEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1564670906833", "PortType_EmployeeEndpoint1"), PortTypeEmployee.class, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeGetAllEmployees
     */
    @WebEndpoint(name = "PortType_GetAllEmployeesEndpoint1")
    public PortTypeGetAllEmployees getPortTypeGetAllEmployeesEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1564670906833", "PortType_GetAllEmployeesEndpoint1"), PortTypeGetAllEmployees.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeGetAllEmployees
     */
    @WebEndpoint(name = "PortType_GetAllEmployeesEndpoint1")
    public PortTypeGetAllEmployees getPortTypeGetAllEmployeesEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1564670906833", "PortType_GetAllEmployeesEndpoint1"), PortTypeGetAllEmployees.class, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeGetEmployee
     */
    @WebEndpoint(name = "PortType_GetEmployeeEndpoint1")
    public PortTypeGetEmployee getPortTypeGetEmployeeEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1564670906833", "PortType_GetEmployeeEndpoint1"), PortTypeGetEmployee.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeGetEmployee
     */
    @WebEndpoint(name = "PortType_GetEmployeeEndpoint1")
    public PortTypeGetEmployee getPortTypeGetEmployeeEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1564670906833", "PortType_GetEmployeeEndpoint1"), PortTypeGetEmployee.class, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeUpdateEmployee
     */
    @WebEndpoint(name = "PortType_UpdateEmployeeEndpoint1")
    public PortTypeUpdateEmployee getPortTypeUpdateEmployeeEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1564670906833", "PortType_UpdateEmployeeEndpoint1"), PortTypeUpdateEmployee.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeUpdateEmployee
     */
    @WebEndpoint(name = "PortType_UpdateEmployeeEndpoint1")
    public PortTypeUpdateEmployee getPortTypeUpdateEmployeeEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1564670906833", "PortType_UpdateEmployeeEndpoint1"), PortTypeUpdateEmployee.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICE_EXCEPTION!= null) {
            throw SERVICE_EXCEPTION;
        }
        return SERVICE_WSDL_LOCATION;
    }

}
