
package com.polarising.bootsecurity.soap.transaction.example.xmlns._1564747039855;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.polarising.bootsecurity.soap.transaction.tibco.schemas.payment.InputPayment;
import com.polarising.bootsecurity.soap.transaction.tibco.schemas.payment.OutputPayment;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PortType_Payment", targetNamespace = "http://xmlns.example.com/1564747039855")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
	com.polarising.bootsecurity.soap.transaction.tibco.schemas.deposit.ObjectFactory.class,
	com.polarising.bootsecurity.soap.transaction.tibco.schemas.getbyid.ObjectFactory.class,
	com.polarising.bootsecurity.soap.transaction.tibco.schemas.payment.ObjectFactory.class,
	com.polarising.bootsecurity.soap.transaction.tibco.schemas.transaction.ObjectFactory.class,
	com.polarising.bootsecurity.soap.transaction.tibco.schemas.transfer.ObjectFactory.class,
	com.polarising.bootsecurity.soap.transaction.tibco.schemas.withdraw.ObjectFactory.class,
	com.polarising.bootsecurity.soap.transaction.tibco.schemas.getbyiban.ObjectFactory.class
})
public interface PortTypePayment {


    /**
     * 
     * @param input
     * @return
     *     returns com.tibco.schemas.bankrising.schemas.payment.OutputPayment
     */
    @WebMethod(operationName = "WritePayment", action = "/Transactions/Service.serviceagent/PortType_PaymentEndpoint1/WritePayment")
    @WebResult(name = "outputPayment", targetNamespace = "http://www.tibco.com/schemas/Bankrising/Schemas/Payment.xsd", partName = "output")
    public OutputPayment writePayment(
        @WebParam(name = "inputPayment", targetNamespace = "http://www.tibco.com/schemas/Bankrising/Schemas/Payment.xsd", partName = "input")
        InputPayment input);

}
