
package com.polarising.bootsecurity.soap.example.xmlns._1564753203144;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AppService", targetNamespace = "http://xmlns.example.com/1564753203144", wsdlLocation = "http://localhost:8074/bankrising/ws/test.wsdl")
public class AppService
    extends Service
{

    private final static URL APPSERVICE_WSDL_LOCATION;
    private final static WebServiceException APPSERVICE_EXCEPTION;
    private final static QName APPSERVICE_QNAME = new QName("http://xmlns.example.com/1564753203144", "AppService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8074/bankrising/ws/test.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APPSERVICE_WSDL_LOCATION = url;
        APPSERVICE_EXCEPTION = e;
    }

    public AppService() {
        super(__getWsdlLocation(), APPSERVICE_QNAME);
    }

    public AppService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APPSERVICE_QNAME, features);
    }

    public AppService(URL wsdlLocation) {
        super(wsdlLocation, APPSERVICE_QNAME);
    }

    public AppService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APPSERVICE_QNAME, features);
    }

    public AppService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AppService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PortType
     */
    @WebEndpoint(name = "Endpoint")
    public PortType getEndpoint() {
        return super.getPort(new QName("http://xmlns.example.com/1564753203144", "Endpoint"), PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortType
     */
    @WebEndpoint(name = "Endpoint")
    public PortType getEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1564753203144", "Endpoint"), PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APPSERVICE_EXCEPTION!= null) {
            throw APPSERVICE_EXCEPTION;
        }
        return APPSERVICE_WSDL_LOCATION;
    }

}
