
package com.polarising.bootsecurity.soap.example.xmlns._1564753203144;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.polarising.bootsecurity.soap.tibco.schemas.untitled.schema.MessageIn;
import com.polarising.bootsecurity.soap.tibco.schemas.untitled.schema.MessageOut;
import com.polarising.bootsecurity.soap.tibco.schemas.untitled.schema.ObjectFactory;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PortType", targetNamespace = "http://xmlns.example.com/1564753203144")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PortType {


    /**
     * 
     * @param input
     * @return
     *     returns com.tibco.schemas.untitled.schema.MessageOut
     */
    @WebMethod(operationName = "Operation", action = "/AppService.serviceagent/PortTypeEndpoint1/Operation")
    @WebResult(name = "message_out", targetNamespace = "http://www.tibco.com/schemas/Untitled/Schema.xsd", partName = "output")
    public MessageOut operation(
        @WebParam(name = "message_in", targetNamespace = "http://www.tibco.com/schemas/Untitled/Schema.xsd", partName = "input")
        MessageIn input);

}
