
package com.polarising.bootsecurity.soap.client.example.xmlns._1564670621329;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Service", targetNamespace = "http://xmlns.example.com/1564670621329", wsdlLocation = "http://localhost:8074/bankrising/ws/client.wsdl")
public class ClientService
    extends javax.xml.ws.Service
{

    private final static URL SERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICE_EXCEPTION;
    private final static QName SERVICE_QNAME = new QName("http://xmlns.example.com/1564670621329", "Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8074/bankrising/ws/client.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICE_WSDL_LOCATION = url;
        SERVICE_EXCEPTION = e;
    }

    public ClientService() {
        super(__getWsdlLocation(), SERVICE_QNAME);
    }

    public ClientService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICE_QNAME, features);
    }

    public ClientService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE_QNAME);
    }

    public ClientService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE_QNAME, features);
    }

    public ClientService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeGetClientById
     */
    @WebEndpoint(name = "PortType_GetClientByIdEndpoint1")
    public PortTypeGetClientById getPortTypeGetClientByIdEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1564670621329", "PortType_GetClientByIdEndpoint1"), PortTypeGetClientById.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeGetClientById
     */
    @WebEndpoint(name = "PortType_GetClientByIdEndpoint1")
    public PortTypeGetClientById getPortTypeGetClientByIdEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1564670621329", "PortType_GetClientByIdEndpoint1"), PortTypeGetClientById.class, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeGetAllClients
     */
    @WebEndpoint(name = "PortType_GetAllClientsEndpoint1")
    public PortTypeGetAllClients getPortTypeGetAllClientsEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1564670621329", "PortType_GetAllClientsEndpoint1"), PortTypeGetAllClients.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeGetAllClients
     */
    @WebEndpoint(name = "PortType_GetAllClientsEndpoint1")
    public PortTypeGetAllClients getPortTypeGetAllClientsEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1564670621329", "PortType_GetAllClientsEndpoint1"), PortTypeGetAllClients.class, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeCreateClient
     */
    @WebEndpoint(name = "PortType_CreateClientEndpoint1")
    public PortTypeCreateClient getPortTypeCreateClientEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1564670621329", "PortType_CreateClientEndpoint1"), PortTypeCreateClient.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeCreateClient
     */
    @WebEndpoint(name = "PortType_CreateClientEndpoint1")
    public PortTypeCreateClient getPortTypeCreateClientEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1564670621329", "PortType_CreateClientEndpoint1"), PortTypeCreateClient.class, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeUpdateClient
     */
    @WebEndpoint(name = "PortType_UpdateClientEndpoint1")
    public PortTypeUpdateClient getPortTypeUpdateClientEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1564670621329", "PortType_UpdateClientEndpoint1"), PortTypeUpdateClient.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeUpdateClient
     */
    @WebEndpoint(name = "PortType_UpdateClientEndpoint1")
    public PortTypeUpdateClient getPortTypeUpdateClientEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1564670621329", "PortType_UpdateClientEndpoint1"), PortTypeUpdateClient.class, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeGetClientByCc
     */
    @WebEndpoint(name = "PortType_GetClientByCcEndpoint1")
    public PortTypeGetClientByCc getPortTypeGetClientByCcEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1564670621329", "PortType_GetClientByCcEndpoint1"), PortTypeGetClientByCc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeGetClientByCc
     */
    @WebEndpoint(name = "PortType_GetClientByCcEndpoint1")
    public PortTypeGetClientByCc getPortTypeGetClientByCcEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1564670621329", "PortType_GetClientByCcEndpoint1"), PortTypeGetClientByCc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICE_EXCEPTION!= null) {
            throw SERVICE_EXCEPTION;
        }
        return SERVICE_WSDL_LOCATION;
    }

}
