
package com.polarising.bootsecurity.soap.client.example.xmlns._1564670621329;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.polarising.bootsecurity.soap.client.tibco.schemas.client.Root;
import com.polarising.bootsecurity.soap.client.tibco.schemas.getbyclientcc.GetByClientCC;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PortType_GetClientByCc", targetNamespace = "http://xmlns.example.com/1564670621329")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
	com.polarising.bootsecurity.soap.client.tibco.schemas.client.ObjectFactory.class,
	com.polarising.bootsecurity.soap.client.tibco.schemas.getbyid.ObjectFactory.class,
	com.polarising.bootsecurity.soap.client.tibco.schemas.getbyclientcc.ObjectFactory.class
})
public interface PortTypeGetClientByCc {


    /**
     * 
     * @param input
     * @return
     *     returns com.tibco.schemas.bankrising.schemas.client.Root
     */
    @WebMethod(operationName = "Operation", action = "/Client/Service.serviceagent/PortType_GetClientByCcEndpoint1/Operation")
    @WebResult(name = "root", targetNamespace = "http://www.tibco.com/schemas/Bankrising/Schemas/Client.xsd", partName = "output")
    public Root operation(
        @WebParam(name = "GetByClientCC", targetNamespace = "http://www.tibco.com/schemas/tibco/Schemas/GetByClientCC.xsd", partName = "input")
        GetByClientCC input);

}
