
package com.polarising.bootsecurity.soap.client.example.xmlns._1564670621329;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.polarising.bootsecurity.soap.client.tibco.schemas.client.InputClient;
import com.polarising.bootsecurity.soap.client.tibco.schemas.client.OutputClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PortType_CreateClient", targetNamespace = "http://xmlns.example.com/1564670621329")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.polarising.bootsecurity.soap.client.tibco.schemas.client.ObjectFactory.class,
    com.polarising.bootsecurity.soap.client.tibco.schemas.getbyid.ObjectFactory.class,
    com.polarising.bootsecurity.soap.client.tibco.schemas.getbyclientcc.ObjectFactory.class
})
public interface PortTypeCreateClient {


    /**
     * 
     * @param input
     * @return
     *     returns com.tibco.schemas.bankrising.schemas.client.OutputClient
     */
    @WebMethod(operationName = "Operation", action = "/Client/Service.serviceagent/PortType_CreateClientEndpoint1/Operation")
    @WebResult(name = "outputClient", targetNamespace = "http://www.tibco.com/schemas/Bankrising/Schemas/Client.xsd", partName = "output")
    public OutputClient operation(
        @WebParam(name = "inputClient", targetNamespace = "http://www.tibco.com/schemas/Bankrising/Schemas/Client.xsd", partName = "input")
        InputClient input);

}
