
package com.polarising.bootsecurity.soap.user.example.xmlns._1565108737830;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Service", targetNamespace = "http://xmlns.example.com/1565108737830", wsdlLocation = "http://localhost:8074/bankrising/ws/user.wsdl")
public class UserService
    extends javax.xml.ws.Service
{

    private final static URL SERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICE_EXCEPTION;
    private final static QName SERVICE_QNAME = new QName("http://xmlns.example.com/1565108737830", "Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8074/bankrising/ws/user.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICE_WSDL_LOCATION = url;
        SERVICE_EXCEPTION = e;
    }

    public UserService() {
        super(__getWsdlLocation(), SERVICE_QNAME);
    }

    public UserService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICE_QNAME, features);
    }

    public UserService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE_QNAME);
    }

    public UserService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE_QNAME, features);
    }

    public UserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeGetAllUsers
     */
    @WebEndpoint(name = "PortType_GetAllUsersEndpoint1")
    public PortTypeGetAllUsers getPortTypeGetAllUsersEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1565108737830", "PortType_GetAllUsersEndpoint1"), PortTypeGetAllUsers.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeGetAllUsers
     */
    @WebEndpoint(name = "PortType_GetAllUsersEndpoint1")
    public PortTypeGetAllUsers getPortTypeGetAllUsersEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1565108737830", "PortType_GetAllUsersEndpoint1"), PortTypeGetAllUsers.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICE_EXCEPTION!= null) {
            throw SERVICE_EXCEPTION;
        }
        return SERVICE_WSDL_LOCATION;
    }

}
