
package com.polarising.bootsecurity.soap.client_account.example.xmlns._1566480228153;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Service", targetNamespace = "http://xmlns.example.com/1566480228153", wsdlLocation = "http://localhost:8074/bankrising/ws/client_account.wsdl")
public class ClientAccountService
    extends javax.xml.ws.Service
{

    private final static URL SERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICE_EXCEPTION;
    private final static QName SERVICE_QNAME = new QName("http://xmlns.example.com/1566480228153", "Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8074/bankrising/ws/client_account.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICE_WSDL_LOCATION = url;
        SERVICE_EXCEPTION = e;
    }

    public ClientAccountService() {
        super(__getWsdlLocation(), SERVICE_QNAME);
    }

    public ClientAccountService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICE_QNAME, features);
    }

    public ClientAccountService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE_QNAME);
    }

    public ClientAccountService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE_QNAME, features);
    }

    public ClientAccountService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientAccountService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeGetClientAccounts
     */
    @WebEndpoint(name = "PortType_GetClientAccountsEndpoint1")
    public PortTypeGetClientAccounts getPortTypeGetClientAccountsEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1566480228153", "PortType_GetClientAccountsEndpoint1"), PortTypeGetClientAccounts.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeGetClientAccounts
     */
    @WebEndpoint(name = "PortType_GetClientAccountsEndpoint1")
    public PortTypeGetClientAccounts getPortTypeGetClientAccountsEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1566480228153", "PortType_GetClientAccountsEndpoint1"), PortTypeGetClientAccounts.class, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeDeleteAccountClient
     */
    @WebEndpoint(name = "PortType_DeleteAccountClientEndpoint1")
    public PortTypeDeleteAccountClient getPortTypeDeleteAccountClientEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1566480228153", "PortType_DeleteAccountClientEndpoint1"), PortTypeDeleteAccountClient.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeDeleteAccountClient
     */
    @WebEndpoint(name = "PortType_DeleteAccountClientEndpoint1")
    public PortTypeDeleteAccountClient getPortTypeDeleteAccountClientEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1566480228153", "PortType_DeleteAccountClientEndpoint1"), PortTypeDeleteAccountClient.class, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeGetAccountClients
     */
    @WebEndpoint(name = "PortType_GetAccountClientsEndpoint1")
    public PortTypeGetAccountClients getPortTypeGetAccountClientsEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1566480228153", "PortType_GetAccountClientsEndpoint1"), PortTypeGetAccountClients.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeGetAccountClients
     */
    @WebEndpoint(name = "PortType_GetAccountClientsEndpoint1")
    public PortTypeGetAccountClients getPortTypeGetAccountClientsEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1566480228153", "PortType_GetAccountClientsEndpoint1"), PortTypeGetAccountClients.class, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeAddClientToAccount
     */
    @WebEndpoint(name = "PortType_AddClientToAccountEndpoint1")
    public PortTypeAddClientToAccount getPortTypeAddClientToAccountEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1566480228153", "PortType_AddClientToAccountEndpoint1"), PortTypeAddClientToAccount.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeAddClientToAccount
     */
    @WebEndpoint(name = "PortType_AddClientToAccountEndpoint1")
    public PortTypeAddClientToAccount getPortTypeAddClientToAccountEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1566480228153", "PortType_AddClientToAccountEndpoint1"), PortTypeAddClientToAccount.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICE_EXCEPTION!= null) {
            throw SERVICE_EXCEPTION;
        }
        return SERVICE_WSDL_LOCATION;
    }

}
