<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/tibco/Schemas/Schema.xsd" xmlns:tns="http://xmlns.example.com/1565108534702" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1565108534702">
    <import namespace="http://www.tibco.com/schemas/tibco/Schemas/Schema.xsd" location="../Schemas/User.xsd"/>
    <message name="GetAllUsersInput"/>
    <message name="GetAllUsersOutput">
        <part name="output" element="ns:root"/>
    </message>
    <portType name="PortType_GetAllUsers">
        <operation name="Operation">
            <input message="tns:GetAllUsersInput"/>
            <output message="tns:GetAllUsersOutput"/>
        </operation>
    </portType>
</definitions>