
package com.polarising.bootsecurity.soap.account.example.xmlns._1564670090695;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Service", targetNamespace = "http://xmlns.example.com/1564670090695", wsdlLocation = "http://localhost:8074/bankrising/ws/account.wsdl")
public class AccountService
    extends javax.xml.ws.Service
{

    private final static URL SERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICE_EXCEPTION;
    private final static QName SERVICE_QNAME = new QName("http://xmlns.example.com/1564670090695", "Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8074/bankrising/ws/account.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICE_WSDL_LOCATION = url;
        SERVICE_EXCEPTION = e;
    }

    public AccountService() {
        super(__getWsdlLocation(), SERVICE_QNAME);
    }

    public AccountService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICE_QNAME, features);
    }

    public AccountService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE_QNAME);
    }

    public AccountService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE_QNAME, features);
    }

    public AccountService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeGetAccountById
     */
    @WebEndpoint(name = "PortType_GetAccountByIdEndpoint1")
    public PortTypeGetAccountById getPortTypeGetAccountByIdEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1564670090695", "PortType_GetAccountByIdEndpoint1"), PortTypeGetAccountById.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeGetAccountById
     */
    @WebEndpoint(name = "PortType_GetAccountByIdEndpoint1")
    public PortTypeGetAccountById getPortTypeGetAccountByIdEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1564670090695", "PortType_GetAccountByIdEndpoint1"), PortTypeGetAccountById.class, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeUpdateAccount
     */
    @WebEndpoint(name = "PortType_UpdateAccountEndpoint1")
    public PortTypeUpdateAccount getPortTypeUpdateAccountEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1564670090695", "PortType_UpdateAccountEndpoint1"), PortTypeUpdateAccount.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeUpdateAccount
     */
    @WebEndpoint(name = "PortType_UpdateAccountEndpoint1")
    public PortTypeUpdateAccount getPortTypeUpdateAccountEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1564670090695", "PortType_UpdateAccountEndpoint1"), PortTypeUpdateAccount.class, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeGetAccountByIban
     */
    @WebEndpoint(name = "PortType_GetAccountByIbanEndpoint1")
    public PortTypeGetAccountByIban getPortTypeGetAccountByIbanEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1564670090695", "PortType_GetAccountByIbanEndpoint1"), PortTypeGetAccountByIban.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeGetAccountByIban
     */
    @WebEndpoint(name = "PortType_GetAccountByIbanEndpoint1")
    public PortTypeGetAccountByIban getPortTypeGetAccountByIbanEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1564670090695", "PortType_GetAccountByIbanEndpoint1"), PortTypeGetAccountByIban.class, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeGetAllAccounts
     */
    @WebEndpoint(name = "PortType_GetAllAccountsEndpoint1")
    public PortTypeGetAllAccounts getPortTypeGetAllAccountsEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1564670090695", "PortType_GetAllAccountsEndpoint1"), PortTypeGetAllAccounts.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeGetAllAccounts
     */
    @WebEndpoint(name = "PortType_GetAllAccountsEndpoint1")
    public PortTypeGetAllAccounts getPortTypeGetAllAccountsEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1564670090695", "PortType_GetAllAccountsEndpoint1"), PortTypeGetAllAccounts.class, features);
    }

    /**
     * 
     * @return
     *     returns PortTypeCreateAccount
     */
    @WebEndpoint(name = "PortType_CreateAccountEndpoint1")
    public PortTypeCreateAccount getPortTypeCreateAccountEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1564670090695", "PortType_CreateAccountEndpoint1"), PortTypeCreateAccount.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortTypeCreateAccount
     */
    @WebEndpoint(name = "PortType_CreateAccountEndpoint1")
    public PortTypeCreateAccount getPortTypeCreateAccountEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1564670090695", "PortType_CreateAccountEndpoint1"), PortTypeCreateAccount.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICE_EXCEPTION!= null) {
            throw SERVICE_EXCEPTION;
        }
        return SERVICE_WSDL_LOCATION;
    }

}
